### PR TITLE
Tiny tweaks

### PR DESCRIPTION
**Pull request by ozxybox**
I renamed a folder, added to the gitignore, and tweaked the run batch file

### CODE REVIEW

**Comment by 1upD** [comment]
Could the run batch file be set to use relative paths? Neither the earlier committed bat file nor this one will work for me - every user might have a different Steam directory set up.

**Comment by 1upD** [comment]
What are all the files changed in the 'added more filters' commit for?

**Comment by ozxybox** [comment]
I thought renaming the folder mod to something more like the mod's name would make more sense.
Those files changed in the added more filters commit were on accident whoops.
Those files are created by vpc I think?
My solution to the batch, other than this, has been just setting up the vs debug stuff and using that.
I tweaked it since that path was a lot more fixed then what it could be, and I forgot steam could be installed to different paths.

**Comment by 1upD** [comment]
> I thought renaming the folder mod to something more like the mod's name would make more sense.
> Those files changed in the added more filters commit were on accident whoops.
> Those files are created by vpc I think?
> My solution to the batch, other than this, has been just setting up the vs debug stuff and using that.
> I tweaked it since that path was a lot more fixed then what it could be, and I forgot steam could be installed to different paths.

Regarding renaming 'mod' to 'lab', I don't think it makes sense to call the folder 'lab' because the two files in that folder are not specific to this MapLabs. They are available for other mods as well.

**Comment by ozxybox** [comment]
Since this is smc map lab, I feel it makes sense to name it lab, but I get what you mean.

**Comment by DevOpacity** [comment]
Uhh, don't really see any point in renaming it.

**Pull request closed without merging**
