### PR TITLE
added handviewmodels and logic_labplayerproxy

### PR DESCRIPTION
**Pull request by ozxybox**
allows mappers to change the viewmodel hands

### CODE REVIEW

**Comment by 1upD** [comment]
Apologies for the redundant comments. I had issues posting my comments and it must have submit multiple times.

**Comment by 1upD** [comment]
One last question - will these changes break the mod without the new hand models? I'm a little nervous about that.

**Comment by ozxybox** [comment]
Probably since it doesn't have a default model set, but there are no separated viewmodels at the moment.
Once we get new models it will become a problem but will be an easy fix.

**Comment by 1upD** [comment]
I pulled your changes, built, and tested out my map. Everything seems to be working normally. My fears are relieved.

So do the viewmodel changes only take effect if you us a logic_labplayerproxy in your map?

**Comment by ozxybox** [comment]
Viewmodel only changes if the ent tells it to change.

**Pull request merged**
